volumes:
  keycloak:
    name: keycloak
  postgres:
    name: postgres
  service:

services:
  postgresql-micro:
    image: postgres:alpine3.15
    hostname: postgresql
    environment:
      - POSTGRES_MULTIPLE_DATABASES=products,orders
      - POSTGRES_DB=cart
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - service:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  postgresql:
    image: postgres:alpine3.15
    hostname: postgresql
    environment:
      - POSTGRES_DB=microecommerce
      - POSTGRES_USER=thomas
      - POSTGRES_PASSWORD=thomas
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.1
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgresql
      - KC_DB_URL_DATABASE=microecommerce
      - KC_DB_USERNAME=thomas
      - KC_DB_PASSWORD=thomas
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=AdminPass1
      - KC_LOG_LEVEL=INFO,org.hibernate:debug,org.hibernate.hql.internal.ast:info
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9091:9090"
#    depends_on:
#      - keycloak
#
#  grafana:
#    image: grafana/grafana:9.5.6
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    depends_on:
#      - prometheus
