volumes:
  keycloak:
    name: keycloak
  postgres:
    name: postgres

services:
  postgresql:
    image: postgres:alpine3.15
    hostname: postgresql
    environment:
      - POSTGRES_DB=microecommerce
      - POSTGRES_USER=thomas
      - POSTGRES_PASSWORD=thomas
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.1
    command: start-dev
#    command: start-dev --https-key-store-file=/etc/x509/https/ecommerce.p12 --https-key-store-password=changeit --hostname=localhost
#    volumes:
#      - ./realm/ecommerce.p12:/etc/x509/https/ecommerce.p12
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgresql
      - KC_DB_URL_DATABASE=microecommerce
      - KC_DB_USERNAME=thomas
      - KC_DB_PASSWORD=thomas
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=AdminPass1
    ports:
      - "9090:8080"
    depends_on:
      - postgresql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    depends_on:
      - keycloak

  grafana:
    image: grafana/grafana:9.5.6
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
