version: "3.9"

volumes:
  keycloak:
    name: keycloak
  postgres:
    name: postgres

services:
  postgresql:
    image: postgres:alpine3.15
    hostname: postgresql
    environment:
      - POSTGRES_DB=microecommerce
      - POSTGRES_USER=thomas
      - POSTGRES_PASSWORD=thomas
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  microecommerce:
#    image: postgres:alpine3.15
#    hostname: microecommerce
#    environment:
#      - POSTGRES_DB=microecommerce
#      - POSTGRES_USER=thomas
#      - POSTGRES_PASSWORD=thomas
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - microecommerce:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
#    networks:
#      - test
  keycloak:
    image: bitnami/keycloak:latest
    environment:
      - KEYCLOAK_DATABASE_NAME=microecommerce
      - KEYCLOAK_DATABASE_USER=thomas
      - KEYCLOAK_DATABASE_PASSWORD=thomas
    ports:
      - "9090:8080"
    depends_on:
      - postgresql
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"