spring:
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/orders
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
    zipkin:
      base-url: http://localhost:9411
  application:
    name: orders-service

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

