spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/v1/cart/**
              filters:
                - PreserveHostHeader=true
            - id: products-service
              uri: lb://products-service
              predicates:
                - Path=/api/v1/product/**
              filters:
                - PreserveHostHeader=true
            - id: orders-service
              uri: lb://orders-service
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - PreserveHostHeader=true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8085



