spring:
  application:
    name: cart-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/cart
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

keycloak:
  realm: ecommerce
  auth-server-url: http://localhost:9090/auth
  resource: spring-microservice-products
  public-client: true
  bearer-only: true

feign:
  client:
    config:
      default:
        loggerLevel: full
