spring:
  application:
    name: products-service
  datasource:
    username: thomas
    password: thomas
    url: jdbc:postgresql://localhost:5432/microecommerce
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

