spring:
  application:
    name: products-service
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  flyway:
    enabled: false
server:
  port: 8081

eureka:
  client:
    enabled: false

keycloak:
  enabled: true

